### ISSUE TITLE
401 error code for pulling sidebar_template.json

### ISSUE THREAD

**Issue by HardTacos** [chromakode/reddit-sidebar-updater#1]
`
Request failed for https://oauth.reddit.com/r/thehardtacos/wiki/sidebar_template.json returned code 401. Truncated server response: {"error": 401} (use muteHttpExceptions option to examine full response) (line 67, file "Code")
`

I have created a wiki page called sidebar_template
I have set my mod account to 'wiki' only

Any ideas why I am receiving this error?

**Comment by chromakode** [comment]
Were you able to resolve this?

**Comment by HardTacos** [comment]
Yes, I did not have my reddit app set to script. Thanks!
