### ISSUE TITLE
issue installing it

### ISSUE THREAD

**Issue by wawinwawin** [chromakode/reddit-sidebar-updater#2]
Hi, I'm  getting the following error when trying to run the bot on a subreddit 

`TypeError: Cannot call method "getEvents" of null. (line 88, file "Code")
`

**Comment by chromakode** [comment]
This might be caused by an invalid value in the `var CALENDAR = ''` line. Could you please share what you have there? (that value should be fine to post publicly, but feel free to email me if you'd prefer)

**Comment by wawinwawin** [comment]
Hi, I did it all again from scratch and it worked so I'm thinking there was no issue and maybe I had simply deleted something by mistake. Sorry for the mixup.

**Comment by chromakode** [comment]
Glad to hear you got it working!
