### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by ghost** [chromakode/reddit-sidebar-updater#3]
I've completed all of what I think are the correct install instructions. But the {{SCHEDULE}} still appears in my sidebar_template wiki site. Nothing ever gets written to config/sidebar. I have confirmed that the username and password are correct and have wiki permissions and config. 

Secondly what value for var CALENDAR do I use from Google Calendar, currently I am using ical link.

I'd love to get this working as it looks great in r/space!

**Comment by chromakode** [comment]
Sounds like the script may not have run. `{{SCHEDULE}}` should appear in your sidebar template wiki page: it's your way of configuring how the sidebar should be structured. When the script runs, it replaces `{{SCHEDULE}}` with the formatted calendar, putting it in the `config/sidebar` wiki page.

As for the calendar id, it should look something like this `abcdefhijklmnop@calendar.google.com`. You can find it in the details for a calendar in the Google Calendar preferences -- right by where you may have got the ical link.

Hope this helps! :smile:

**Comment by ghost** [comment]
Totally does, this works now! Thank you & its awesome.

**Comment by chromakode** [comment]
Glad to hear it! I've updated the comments a bit to hopefully explain this better for future users. :+1:

**Comment by ghost** [comment]
Yeah mon! Great work btw.
